import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "./utils/font";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body className={`${plusJakartaSans.variable} light h-[100%]`}>
				<Toaster position="top-right" />
				{children}
			</body>
		</html>
	);
}
