import type { Metadata } from "next";
import "./globals.css";
import Body from "./components/Body";

export const metadata: Metadata = {
  title: "Kanban Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<Body children={children}/>
		</html>
	);
}
