import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "./utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body className={`${plusJakartaSans.variable}light h-[100%]`}>
				{children}
			</body>
		</html>
	);
}
